# Generated by Django 3.2 on 2021-12-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_allproduct_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproduct',
            old_name='stock',
            new_name='instock',
        ),
    ]
