# Generated by Django 4.0.1 on 2022-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_orderlist_orderpending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpending',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
