# Generated by Django 4.0.1 on 2022-02-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_orderpending_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='sliptime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
