# Generated by Django 3.2 on 2022-06-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_catagory_allproduct_catagoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
